apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer-service
  name: producer-service
  namespace: kafka
spec:
  ports:
    - name: producer-port
      port: 80
      targetPort: 9376
  selector:
    app: producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: kafka-producer
          imagePullPolicy: IfNotPresent
          name: producer
          ports:
            - containerPort: 80
